blank_issues_enabled: true
contact_links:
  - name: Questions
    url: https://github.com/CoderSixSix/test-achievements/discussions/categories/q-a
    about: Please ask and answer questions in discussions.
  - name: Ideas
    url: https://github.com/CoderSixSix/test-achievements/discussions/categories/ideas
    about: Please share ideas in discussions.
